import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { sendEmail } from "@/lib/ses.server";
import { useAuth } from "@/lib/auth";
import { PolarisShell } from "@/components/platform/PolarisShell";
import { RequestStatusBadge } from "@/components/seaport/RequestStatusBadge";
import { SLATimer } from "@/components/seaport/SLATimer";
import { Button } from "@/components/ui/button";
import { Loader2, Plane, CheckCircle2, XCircle, FileText } from "lucide-react";
import { toast } from "sonner";

// ─── Completion report (#126): build a summary + email it, mark report_sent ────
const doSendSeaportReport = createServerFn({ method: "POST" })
  // @ts-expect-error validator() not available in this version
  .handler(async (ctx: { data: { requestId: string } }) => {
    const { requestId } = ctx.data;
    const { data: req } = await (supabaseAdmin as any)
      .from("seaport_requests")
      .select("request_id, request_date, status, submitted_by, completed_at, yachts:vessel_id(vessel_name)")
      .eq("request_id", requestId).single();
    if (!req) throw new Error("Request not found");

    const [{ data: arr }, { data: dep }] = await Promise.all([
      (supabaseAdmin as any).from("seaport_arrivals").select("crew_name, flight_number, flight_date, status").eq("request_id", requestId),
      (supabaseAdmin as any).from("seaport_departures").select("crew_name, flight_number, flight_date, status").eq("request_id", requestId),
    ]);

    const row = (r: any) => `<tr><td style="padding:4px 8px;border:1px solid #ddd">${r.crew_name}</td><td style="padding:4px 8px;border:1px solid #ddd">${r.flight_number ?? "—"}</td><td style="padding:4px 8px;border:1px solid #ddd">${r.flight_date ?? "—"}</td><td style="padding:4px 8px;border:1px solid #ddd">${r.status}</td></tr>`;
    const section = (title: string, rows: any[]) =>
      `<h3>${title}</h3>${rows.length ? `<table style="border-collapse:collapse;width:100%"><thead><tr><th style="padding:4px 8px;border:1px solid #ddd;text-align:left">Crew</th><th style="padding:4px 8px;border:1px solid #ddd;text-align:left">Flight</th><th style="padding:4px 8px;border:1px solid #ddd;text-align:left">Date</th><th style="padding:4px 8px;border:1px solid #ddd;text-align:left">Result</th></tr></thead><tbody>${rows.map(row).join("")}</tbody></table>` : "<p>None</p>"}`;

    const vesselName = req.yachts?.vessel_name ?? "Vessel";
    const html = `<div style="font-family:Arial,sans-serif"><h2>Seaport Immigration — Completion Report</h2>
      <p><strong>${vesselName}</strong> · week of ${req.request_date}</p>
      ${section("Arrivals (Sign On)", arr ?? [])}
      ${section("Departures (Sign Off)", dep ?? [])}
      <p style="color:#666;font-size:12px;margin-top:16px">Generated by Polaris — JLS Yachts.</p></div>`;
    const text = `Seaport Immigration Completion Report — ${vesselName}, week of ${req.request_date}.`;

    // Recipient: the submitter's email acts as the vessel contact (yachts has no
    // contact-email field yet — see follow-up note).
    let to = "itsupport@jlsyachts.com";
    try {
      const { data: u } = await (supabaseAdmin as any).auth.admin.getUserById(req.submitted_by);
      if (u?.user?.email) to = u.user.email;
    } catch { /* fall back to support inbox */ }

    let emailed = false;
    try { await sendEmail({ to: [to], subject: `Seaport Completion Report — ${vesselName}`, html, text }); emailed = true; }
    catch (e) { console.error("Seaport report email failed:", e); }

    const now = new Date().toISOString();
    await (supabaseAdmin as any).from("seaport_requests").update({
      status: "report_sent",
      completed_at: req.completed_at ?? now,
      report_sent_at: now,
    }).eq("request_id", requestId);

    return { emailed, to };
  });

export const Route = createFileRoute("/_app/seaport/$requestId")({
  component: SeaportDetail,
  head: () => ({ meta: [{ title: "Seaport Request — Polaris" }] }),
});

const fmtDate = (d: string | null) => d ? new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) : "—";

function SeaportDetail() {
  const { requestId } = Route.useParams();
  const { user } = useAuth();
  const qc = useQueryClient();

  const { data, isLoading, refetch } = useQuery({
    queryKey: ["seaport-request", requestId],
    queryFn: async () => {
      const [{ data: req }, { data: arr }, { data: dep }, { data: sla }] = await Promise.all([
        (supabase as any).from("seaport_requests").select("*, yachts:vessel_id(vessel_name, vessel_type)").eq("request_id", requestId).single(),
        (supabase as any).from("seaport_arrivals").select("*").eq("request_id", requestId).order("created_at"),
        (supabase as any).from("seaport_departures").select("*").eq("request_id", requestId).order("created_at"),
        (supabase as any).from("seaport_sla").select("*").eq("request_id", requestId).maybeSingle(),
      ]);
      return { req, arr: arr ?? [], dep: dep ?? [], sla };
    },
  });

  async function setRequestStatus(patch: Record<string, any>) {
    const { error } = await (supabase as any).from("seaport_requests").update(patch).eq("request_id", requestId);
    if (error) { toast.error(error.message); return; }
    qc.invalidateQueries({ queryKey: ["seaport-request", requestId] });
    qc.invalidateQueries({ queryKey: ["seaport-queue"] });
  }

  async function setRowStatus(table: "seaport_arrivals" | "seaport_departures", idCol: string, id: string, status: string) {
    const patch: Record<string, any> = { status };
    if (status === "completed") { patch.executed_at = new Date().toISOString(); patch.executed_by = user?.id ?? null; }
    const { error } = await (supabase as any).from(table).update(patch).eq(idCol, id);
    if (error) { toast.error(error.message); return; }
    refetch();
  }

  async function sendReport() {
    try {
      const res = await doSendSeaportReport({ data: { requestId } });
      toast.success(res.emailed ? `Report sent to ${res.to}` : `Report generated (email unavailable — recorded)`);
      refetch(); qc.invalidateQueries({ queryKey: ["seaport-queue"] });
    } catch (e: any) { toast.error(e.message ?? "Could not send report"); }
  }

  if (isLoading || !data?.req) {
    return <PolarisShell label="Polaris / Port & Agency" title="Seaport Request"><div className="flex h-40 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div></PolarisShell>;
  }

  const { req, arr, dep, sla } = data;
  const allRows = [...arr, ...dep];
  const allDone = allRows.length > 0 && allRows.every((r: any) => ["completed", "no_show", "cancelled"].includes(r.status));
  const done = req.status === "completed" || req.status === "report_sent";

  return (
    <PolarisShell
      label="Polaris / Port & Agency"
      title={`${req.yachts?.vessel_name ?? "Vessel"} — ${fmtDate(req.request_date)}`}
      workspace={{ type: "vessel", label: req.yachts?.vessel_name ?? "" }}
      actions={
        <div className="flex items-center gap-2">
          <RequestStatusBadge status={req.status} />
          {req.status === "submitted" && (
            <Button size="sm" variant="outline" onClick={() => setRequestStatus({ status: "acknowledged", acknowledged_at: new Date().toISOString(), acknowledged_by: user?.id })}>Acknowledge</Button>
          )}
          {(req.status === "acknowledged" || req.status === "in_progress") && (
            <Button size="sm" disabled={!allDone} onClick={() => setRequestStatus({ status: "completed", completed_at: new Date().toISOString() })}>Mark complete</Button>
          )}
          {req.status === "completed" && (
            <Button size="sm" className="gap-1.5" onClick={sendReport}><FileText className="h-4 w-4" /> Send report</Button>
          )}
        </div>
      }
    >
      {sla?.submitted_at && (
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">SLA (4-hour completion target)</div>
          <SLATimer submittedAt={sla.submitted_at} targetMins={sla.sla_target_mins ?? 240} completedAt={done ? req.completed_at : null} />
        </div>
      )}

      <RowTable title="Arrivals (Sign On)" rows={arr} idCol="arrival_id" table="seaport_arrivals" onSet={setRowStatus} locked={done} />
      <RowTable title="Departures (Sign Off)" rows={dep} idCol="departure_id" table="seaport_departures" onSet={setRowStatus} locked={done} />

      {req.notes && <div className="rounded-xl border border-border bg-card p-4 text-sm"><span className="text-muted-foreground">Notes: </span>{req.notes}</div>}
    </PolarisShell>
  );
}

function RowTable({ title, rows, idCol, table, onSet, locked }: {
  title: string; rows: any[]; idCol: string; table: "seaport_arrivals" | "seaport_departures";
  onSet: (t: any, idCol: string, id: string, status: string) => void; locked: boolean;
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-border">
      <div className="border-b border-border/60 bg-muted/30 px-4 py-2.5 text-sm font-semibold">{title} <span className="text-muted-foreground/70">({rows.length})</span></div>
      {rows.length === 0 ? (
        <p className="px-4 py-4 text-center text-[13px] text-muted-foreground/70">None</p>
      ) : (
        <table className="w-full text-sm">
          <tbody className="divide-y divide-border">
            {rows.map((r: any) => (
              <tr key={r[idCol]}>
                <td className="px-4 py-2.5">
                  <div className="font-medium">{r.crew_name}</div>
                  <div className="text-[11px] text-muted-foreground">
                    {r.flight_number ?? "—"} · {fmtDate(r.flight_date)} {r.flight_time ?? ""}{r.pickup_required ? ` · pickup ${r.pickup_time ?? ""}` : ""}{r.crew_contact ? ` · ${r.crew_contact}` : ""}
                  </div>
                </td>
                <td className="px-4 py-2.5"><RequestStatusBadge status={r.status} /></td>
                <td className="px-4 py-2.5 text-right">
                  {!locked && r.status !== "completed" && (
                    <div className="inline-flex gap-1">
                      <Button size="sm" variant="ghost" className="h-7 gap-1 text-xs text-emerald-400" onClick={() => onSet(table, idCol, r[idCol], "completed")}><CheckCircle2 className="h-3.5 w-3.5" /> Done</Button>
                      <Button size="sm" variant="ghost" className="h-7 gap-1 text-xs text-muted-foreground hover:text-red-400" onClick={() => onSet(table, idCol, r[idCol], "no_show")}><XCircle className="h-3.5 w-3.5" /> No-show</Button>
                    </div>
                  )}
                  {r.status === "completed" && <span className="inline-flex items-center gap-1 text-[11px] text-emerald-400"><Plane className="h-3.5 w-3.5" /> {fmtDate(r.executed_at)}</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
