/**
 * Orbit 2 — EHS NOC Record.
 *
 * A spreadsheet, deliberately: no side panel, no dialog. Click a cell, type,
 * move on. That is how this register is kept today and the spec asks for the
 * same feel, so the screen is a grid where every cell is the input.
 *
 * Saving is per cell on blur rather than a Save button — a grid with a single
 * Save invites a page of edits to be lost in one navigation.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { Loader2, Plus, Search, Paperclip, Upload, X, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { guardUploadFile, uploadContentType } from "@/lib/upload-guard";
import { storageRef } from "@/lib/signed-url";
import { SignedAnchor } from "@/components/ui/signed-file";
import { ORBIT2_BUCKET, suggestionsFor, matchSuggestions, type Orbit2Noc, type Orbit2NocStatus } from "./orbit2-data";
import { inputCls } from "./orbit2-fields";

const sb = supabase as any;

const NOC_STATUSES: Orbit2NocStatus[] = ["To be Invoiced", "Invoiced"];
type NocView = "all" | Orbit2NocStatus;
const NOC_VIEWS: { key: NocView; label: string }[] = [
  { key: "all", label: "All EHS NOC" },
  { key: "To be Invoiced", label: "To be Invoiced" },
  { key: "Invoiced", label: "Invoiced" },
];

/** MMM DD, YYYY — how the spec asks NOC dates to read. */
function fmtDate(iso: string | null): string {
  if (!iso) return "";
  return new Date(`${iso}T00:00:00`).toLocaleDateString("en-US", {
    month: "short", day: "2-digit", year: "numeric",
  });
}

export function Orbit2Noc({
  rows, loading, reload, clientPool,
}: {
  rows: Orbit2Noc[];
  loading: boolean;
  reload: () => Promise<void> | void;
  clientPool: string[];
}) {
  const { user } = useAuth();
  const [query, setQuery] = useState("");
  const [adding, setAdding] = useState(false);
  const [view, setView] = useState<NocView>("all");

  const clientOptions = useMemo(
    () => suggestionsFor(rows.map((r) => r.client_name), clientPool),
    [rows, clientPool],
  );
  const typeOptions = useMemo(() => suggestionsFor(rows.map((r) => r.noc_type)), [rows]);
  const requesterOptions = useMemo(() => suggestionsFor(rows.map((r) => r.requested_by)), [rows]);

  const viewCounts = useMemo(() => {
    const counts: Record<NocView, number> = { all: rows.length, "To be Invoiced": 0, Invoiced: 0 };
    for (const r of rows) counts[r.status] += 1;
    return counts;
  }, [rows]);

  const filtered = useMemo(() => {
    const byView = view === "all" ? rows : rows.filter((r) => r.status === view);
    const q = query.trim().toLowerCase();
    if (!q) return byView;
    return byView.filter((r) =>
      [r.ref_id, r.client_name, r.noc_type, r.requested_by, r.invoice_number]
        .some((v) => (v ?? "").toLowerCase().includes(q)));
  }, [rows, query, view]);

  /** Write one cell. The Ref ID is generated by the database, never sent. */
  async function save(id: string, patch: Record<string, unknown>) {
    const { error } = await sb.from("orbit2_noc_records").update(patch).eq("id", id);
    if (error) { toast.error(error.message); return; }
    await reload();
  }

  async function addRow() {
    setAdding(true);
    try {
      const { data, error } = await sb
        .from("orbit2_noc_records")
        .insert({ created_by: user?.id ?? null })
        .select("ref_id")
        .single();
      if (error) throw error;
      toast.success(`${data.ref_id} added`);
      await reload();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not add a row");
    } finally {
      setAdding(false);
    }
  }

  async function removeRow(r: Orbit2Noc) {
    if (!confirm(`Delete ${r.ref_id}? This cannot be undone.`)) return;
    const { error } = await sb.from("orbit2_noc_records").delete().eq("id", r.id);
    if (error) { toast.error(error.message); return; }
    toast.success(`${r.ref_id} deleted`);
    await reload();
  }

  function exportCsv() {
    const head = ["Ref ID", "Client Name", "NOC Type", "Requested By", "Receipt Date", "Permit Date", "Status", "Invoice Number"];
    const body = rows.map((r) => [
      r.ref_id, r.client_name ?? "", r.noc_type ?? "", r.requested_by ?? "",
      fmtDate(r.receipt_date), fmtDate(r.permit_date), r.status, r.invoice_number ?? "",
    ]);
    const csv = [head, ...body]
      .map((line) => line.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(","))
      .join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `orbit2-ehs-noc-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 10_000);
  }

  if (loading) {
    return <div className="flex h-64 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="flex flex-wrap items-center gap-1 border-b border-border/40 px-5 py-2">
        {NOC_VIEWS.map((v) => (
          <button key={v.key} onClick={() => setView(v.key)}
            className={cn("flex items-center gap-1.5 rounded-md px-3 py-1 text-[15px] font-medium transition",
              view === v.key ? "bg-accent text-foreground" : "text-muted-foreground hover:bg-accent/60")}>
            {v.label}
            <span className={cn("rounded-full px-1.5 py-0.5 text-[13px]",
              view === v.key ? "bg-primary/15 text-primary" : "bg-muted text-muted-foreground")}>
              {viewCounts[v.key]}
            </span>
          </button>
        ))}
      </div>

      <div className="flex items-center justify-between gap-3 border-b border-border/50 px-5 py-3">
        <p className="text-[15px] text-muted-foreground">
          {rows.length === 0 ? "No NOC records yet." : `${filtered.length} of ${rows.length} record${rows.length === 1 ? "" : "s"}`}
        </p>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="pointer-events-none absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <input className={cn(inputCls, "h-9 w-56 py-1 pl-8 text-[15px]")} placeholder="Search"
              value={query} onChange={(e) => setQuery(e.target.value)} />
          </div>
          <button onClick={exportCsv} disabled={!rows.length}
            className="h-9 rounded-md border border-border px-3 text-[15px] font-medium hover:bg-accent disabled:opacity-50">
            Export
          </button>
          <button onClick={() => void addRow()} disabled={adding}
            className="flex h-9 items-center gap-1.5 rounded-md bg-primary px-3 text-[15px] font-medium text-primary-foreground hover:opacity-90 disabled:opacity-50">
            {adding ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />} New Record
          </button>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-auto">
        {filtered.length === 0 ? (
          <div className="flex h-full items-center justify-center px-8 text-center text-[15px] text-muted-foreground">
            {rows.length === 0
              ? "Add a record and fill it in on the grid — the Ref ID is generated for you."
              : view !== "all"
                ? `Nothing in ${view}.`
                : "Nothing matches that search."}
          </div>
        ) : (
          <table className="w-full border-separate border-spacing-0 text-[14px]">
            <thead className="sticky top-0 z-10">
              <tr>
                {["Ref ID", "Client Name", "NOC Type", "Requested By", "Receipt Date",
                  "Permit Date", "NOC Document", "NOC Invoice", "Status", "Invoice Number", ""].map((c) => (
                  <th key={c} className="whitespace-nowrap border-b border-border bg-muted/40 px-3 py-2.5 text-left font-semibold text-muted-foreground backdrop-blur">
                    {c}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((r) => (
                <tr key={r.id} className="hover:bg-muted/20">
                  <td className="whitespace-nowrap border-b border-border/40 px-3 py-1.5 font-semibold text-primary">{r.ref_id}</td>
                  <Cell><SuggestCell value={r.client_name} options={clientOptions} onSave={(v) => save(r.id, { client_name: v })} /></Cell>
                  <Cell><SuggestCell value={r.noc_type} options={typeOptions} onSave={(v) => save(r.id, { noc_type: v })} /></Cell>
                  <Cell><SuggestCell value={r.requested_by} options={requesterOptions} onSave={(v) => save(r.id, { requested_by: v })} /></Cell>
                  <Cell><DateCell value={r.receipt_date} onSave={(v) => save(r.id, { receipt_date: v })} /></Cell>
                  <Cell><DateCell value={r.permit_date} onSave={(v) => save(r.id, { permit_date: v })} /></Cell>
                  <Cell><AttachCell value={r.noc_document} onSave={(v) => save(r.id, { noc_document: v })} /></Cell>
                  <Cell><AttachCell value={r.noc_invoice} onSave={(v) => save(r.id, { noc_invoice: v })} /></Cell>
                  <Cell>
                    <select className={cn(cellCls, "min-w-[9.5rem]")} value={r.status}
                      onChange={(e) => save(r.id, { status: e.target.value })}>
                      {NOC_STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </Cell>
                  <Cell><InvoiceNumberCell value={r.invoice_number} onSave={(v) => save(r.id, { invoice_number: v })} /></Cell>
                  <Cell>
                    <button onClick={() => void removeRow(r)} title={`Delete ${r.ref_id}`}
                      className="rounded p-1 text-muted-foreground hover:bg-destructive/10 hover:text-destructive">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </Cell>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

const Cell = ({ children }: { children: React.ReactNode }) => (
  <td className="border-b border-r border-border/30 px-1 py-1 last:border-r-0">{children}</td>
);

/** Grid inputs are borderless until focused, so the grid reads as a sheet. */
const cellCls =
  "w-full rounded border border-transparent bg-transparent px-2 py-1 text-[14px] outline-none " +
  "hover:border-border/60 focus:border-primary focus:bg-background";

/** Free text with Smart Auto-Suggest, saved when the cell loses focus. */
function SuggestCell({
  value, options, onSave,
}: { value: string | null; options: string[]; onSave: (v: string | null) => void }) {
  const [v, setV] = useState(value ?? "");
  const [open, setOpen] = useState(false);
  const box = useRef<HTMLDivElement>(null);
  useEffect(() => { setV(value ?? ""); }, [value]);
  const matches = matchSuggestions(options, v, 6);

  function commit(next: string) {
    const clean = next.trim();
    setOpen(false);
    if (clean === (value ?? "")) return;
    onSave(clean || null);
  }

  return (
    <div ref={box} className="relative">
      <input className={cellCls} value={v}
        onChange={(e) => { setV(e.target.value); setOpen(true); }}
        onFocus={() => setOpen(true)}
        onBlur={() => { setTimeout(() => setOpen(false), 120); commit(v); }}
        onKeyDown={(e) => { if (e.key === "Enter") (e.target as HTMLInputElement).blur(); }} />
      {open && matches.length > 0 && (
        <ul className="absolute z-30 mt-0.5 max-h-44 w-max min-w-full overflow-auto rounded-md border border-border bg-popover py-1 shadow-lg">
          {matches.map((m) => (
            <li key={m}>
              <button type="button" className="block w-full px-3 py-1 text-left text-[14px] hover:bg-accent"
                onMouseDown={(e) => { e.preventDefault(); setV(m); commit(m); }}>
                {m}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function InvoiceNumberCell({ value, onSave }: { value: string | null; onSave: (v: string | null) => void }) {
  const [v, setV] = useState(value ?? "");
  useEffect(() => { setV(value ?? ""); }, [value]);
  return (
    <input className={cn(cellCls, "min-w-[8.5rem]")} value={v}
      onChange={(e) => setV(e.target.value)}
      onBlur={() => { const clean = v.trim(); if (clean !== (value ?? "")) onSave(clean || null); }}
      onKeyDown={(e) => { if (e.key === "Enter") (e.target as HTMLInputElement).blur(); }} />
  );
}

function DateCell({ value, onSave }: { value: string | null; onSave: (v: string | null) => void }) {
  const [v, setV] = useState(value ?? "");
  useEffect(() => { setV(value ?? ""); }, [value]);
  return (
    <input type="date" className={cn(cellCls, "min-w-[8.5rem]")} value={v}
      onChange={(e) => setV(e.target.value)}
      onBlur={() => { if (v !== (value ?? "")) onSave(v || null); }}
      title={fmtDate(value)} />
  );
}

/**
 * One attachment per cell. Clicking the cell opens the file if there is one;
 * the paperclip replaces it. Only PDFs and images, as elsewhere in the module.
 */
function AttachCell({ value, onSave }: { value: string | null; onSave: (v: string | null) => void }) {
  const [busy, setBusy] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const input = useRef<HTMLInputElement>(null);

  async function pick(file: File | undefined) {
    if (!file) return;
    if (!guardUploadFile(file, { accepts: "Use a PDF or an image." })) return;
    setBusy(true);
    try {
      const path = `orbit2/noc/${crypto.randomUUID()}-${file.name.replace(/[^\w.-]+/g, "_")}`;
      const { error } = await supabase.storage
        .from(ORBIT2_BUCKET)
        .upload(path, file, { contentType: uploadContentType(file), upsert: false });
      if (error) throw error;
      onSave(storageRef(ORBIT2_BUCKET, path));
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Upload failed");
    } finally {
      setBusy(false);
      if (input.current) input.current.value = "";
    }
  }

  return (
    <div
      onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
      onDragLeave={() => setDragOver(false)}
      onDrop={(e) => { e.preventDefault(); setDragOver(false); void pick(e.dataTransfer.files?.[0]); }}
      className={cn("flex min-w-[9rem] items-center gap-1 rounded px-1 transition", dragOver && "bg-primary/10 ring-1 ring-primary")}>
      <input ref={input} type="file" accept="application/pdf,image/*" className="hidden"
        onChange={(e) => void pick(e.target.files?.[0])} />
      {value ? (
        <>
          <SignedAnchor stored={value} className="flex min-w-0 flex-1 items-center gap-1 text-[14px] text-primary hover:underline">
            <Paperclip className="h-3.5 w-3.5 shrink-0" /> <span className="truncate">View</span>
          </SignedAnchor>
          <button onClick={() => onSave(null)} title="Remove attachment"
            className="rounded p-0.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive">
            <X className="h-3.5 w-3.5" />
          </button>
        </>
      ) : (
        <button onClick={() => input.current?.click()} disabled={busy}
          className="flex items-center gap-1 rounded px-1.5 py-0.5 text-[14px] text-muted-foreground hover:bg-accent hover:text-foreground disabled:opacity-50">
          {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />} Attach
        </button>
      )}
    </div>
  );
}
