/**
 * Generate Crew Placement PDFs (contracts & payslips), rendered with pdf-lib.
 * Worker/edge-safe. Contracts fill a {{placeholder}} template body into a branded
 * letterhead with a signature block; payslips render a proper tabular layout.
 */
import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from 'pdf-lib'

const A4 = { w: 595.28, h: 841.89 }
const MARGIN = 56
const NAVY = rgb(0.03, 0.26, 0.37)
const INK = rgb(0.12, 0.14, 0.17)
const MUTED = rgb(0.42, 0.47, 0.52)
const LINE = rgb(0.82, 0.86, 0.9)
const BAND = rgb(0.95, 0.97, 0.98)

/** Replace {{key}} tokens in a template body with values (missing → blank). */
export function fillTemplate(body: string, values: Record<string, string | number | null | undefined>): string {
  return (body ?? '').replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_m, k) => {
    const v = values[k]
    return v == null ? '' : String(v)
  })
}

const fmtMoney = (n: any) =>
  n == null || n === '' ? '—' : Number(n).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

// ── Shared drawing helpers ────────────────────────────────────────────────────
function letterhead(page: PDFPage, bold: PDFFont, font: PDFFont, title: string, subtitle?: string) {
  let y = A4.h - MARGIN
  page.drawText('JLS Yachts LLC', { x: MARGIN, y, size: 16, font: bold, color: NAVY })
  const t = title.toUpperCase()
  page.drawText(t, { x: A4.w - MARGIN - bold.widthOfTextAtSize(t, 15), y, size: 15, font: bold, color: NAVY })
  y -= 14
  page.drawText('Port Operations & Crew Management · Dubai, UAE', { x: MARGIN, y, size: 8.5, font, color: MUTED })
  if (subtitle) {
    page.drawText(subtitle, { x: A4.w - MARGIN - font.widthOfTextAtSize(subtitle, 9), y, size: 9, font, color: MUTED })
  }
  y -= 12
  page.drawLine({ start: { x: MARGIN, y }, end: { x: A4.w - MARGIN, y }, thickness: 1, color: NAVY })
  return y - 24
}

function footer(page: PDFPage, font: PDFFont, text: string) {
  page.drawText(text, { x: MARGIN, y: 30, size: 7.5, font, color: rgb(0.6, 0.64, 0.68) })
}

// ── Contract PDF: branded letterhead + prose body + signature block ───────────
export async function buildContractPdf(
  title: string,
  text: string,
  opts: { docRef?: string; date?: string; signature?: boolean } = {},
): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const maxW = A4.w - MARGIN * 2

  let page = doc.addPage([A4.w, A4.h])
  const sub = [opts.docRef, opts.date].filter(Boolean).join('  ·  ') || undefined
  let y = letterhead(page, bold, font, title, sub)

  const size = 10.5
  const lineH = size * 1.55
  const wrap = (line: string): string[] => {
    if (line === '') return ['']
    const words = line.split(/\s+/)
    const out: string[] = []
    let cur = ''
    for (const w of words) {
      const test = cur ? `${cur} ${w}` : w
      if (font.widthOfTextAtSize(test, size) > maxW && cur) { out.push(cur); cur = w }
      else cur = test
    }
    if (cur) out.push(cur)
    return out
  }

  const newPage = () => { page = doc.addPage([A4.w, A4.h]); y = A4.h - MARGIN }
  for (const raw of (text ?? '').split('\n')) {
    // A line that looks like a heading (ALL CAPS, short) gets bold emphasis.
    const isHeading = /^[A-Z0-9 ,.&'()\/-]{4,}$/.test(raw.trim()) && raw.trim().length < 60 && /[A-Z]/.test(raw)
    for (const line of wrap(raw)) {
      if (y < MARGIN + lineH + 12) newPage()
      page.drawText(line, { x: MARGIN, y, size, font: isHeading ? bold : font, color: isHeading ? NAVY : INK })
      y -= lineH
    }
  }

  // Signature block
  if (opts.signature) {
    if (y < MARGIN + 120) newPage()
    y -= 26
    const colW = (maxW - 40) / 2
    const blocks = [
      { x: MARGIN, label: 'For and on behalf of the Employer', who: 'JLS Yachts LLC' },
      { x: MARGIN + colW + 40, label: 'The Seafarer', who: '' },
    ]
    for (const b of blocks) {
      page.drawLine({ start: { x: b.x, y }, end: { x: b.x + colW, y }, thickness: 0.75, color: LINE })
      page.drawText('Signature', { x: b.x, y: y - 12, size: 8, font, color: MUTED })
      page.drawText(b.label, { x: b.x, y: y - 30, size: 9, font: bold, color: INK })
      if (b.who) page.drawText(b.who, { x: b.x, y: y - 44, size: 9, font, color: INK })
      page.drawText('Date: ______________________', { x: b.x, y: y - 62, size: 9, font, color: MUTED })
    }
  }

  footer(page, font, 'Generated by Polaris — JLS Yachts LLC')
  return doc.save()
}

// Back-compat alias (older callers) — a plain titled text document.
export async function buildTextPdf(title: string, text: string): Promise<Uint8Array> {
  return buildContractPdf(title, text)
}

// ── Payslip PDF: proper tabular earnings / deductions / net-pay layout ────────
type Line = { label: string; amount: number }
export type PayslipData = {
  crewName: string
  rank?: string
  department?: string
  nationality?: string
  vesselName?: string
  employeeId?: string
  period: string
  currency: string
  issuedDate: string
  basic: number
  additions: Line[]
  deductions: Line[]
  bank?: { holder?: string; bankName?: string; iban?: string; bic?: string; country?: string }
}

export async function buildPayslipPdf(d: PayslipData): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const page = doc.addPage([A4.w, A4.h])
  const maxW = A4.w - MARGIN * 2
  let y = letterhead(page, bold, font, 'Payslip', `Pay period: ${d.period}`)

  // Employee / pay meta — two columns of key/value.
  const colGap = 24
  const colW = (maxW - colGap) / 2
  const leftRows: [string, string][] = [
    ['Employee', d.crewName || '—'],
    ['Rank / Position', d.rank || '—'],
    ['Department', d.department || '—'],
    ['Vessel', d.vesselName || '—'],
  ]
  const rightRows: [string, string][] = [
    ['Pay period', d.period],
    ['Payment currency', d.currency || '—'],
    ['Nationality', d.nationality || '—'],
    ['Date issued', d.issuedDate],
  ]
  const rowH = 15
  const drawKV = (rows: [string, string][], x: number) => {
    let yy = y
    for (const [k, v] of rows) {
      page.drawText(k, { x, y: yy, size: 8, font, color: MUTED })
      page.drawText(v, { x, y: yy - 11, size: 10, font: bold, color: INK })
      yy -= rowH + 13
    }
  }
  drawKV(leftRows, MARGIN)
  drawKV(rightRows, MARGIN + colW + colGap)
  y -= (rowH + 13) * 4 + 10

  // Earnings + deductions tables.
  const earnings: Line[] = [{ label: 'Basic salary', amount: Number(d.basic) || 0 }, ...(d.additions ?? [])]
  const totalEarnings = earnings.reduce((s, l) => s + (Number(l.amount) || 0), 0)
  const totalDeductions = (d.deductions ?? []).reduce((s, l) => s + (Number(l.amount) || 0), 0)
  const net = totalEarnings - totalDeductions

  const tableHeader = (label: string) => {
    page.drawRectangle({ x: MARGIN, y: y - 16, width: maxW, height: 20, color: BAND })
    page.drawText(label, { x: MARGIN + 8, y: y - 11, size: 9, font: bold, color: NAVY })
    page.drawText('Amount', { x: A4.w - MARGIN - 8 - bold.widthOfTextAtSize('Amount', 9), y: y - 11, size: 9, font: bold, color: NAVY })
    y -= 24
  }
  const tableRow = (label: string, amount: number, opts: { bold?: boolean } = {}) => {
    const f = opts.bold ? bold : font
    page.drawText(label, { x: MARGIN + 8, y, size: 9.5, font: f, color: INK })
    const amt = `${d.currency} ${fmtMoney(amount)}`
    page.drawText(amt, { x: A4.w - MARGIN - 8 - f.widthOfTextAtSize(amt, 9.5), y, size: 9.5, font: f, color: INK })
    y -= 8
    page.drawLine({ start: { x: MARGIN, y }, end: { x: A4.w - MARGIN, y }, thickness: 0.5, color: LINE })
    y -= 12
  }

  tableHeader('EARNINGS')
  for (const l of earnings) tableRow(l.label || 'Item', Number(l.amount) || 0)
  tableRow('Total earnings', totalEarnings, { bold: true })
  y -= 8

  tableHeader('DEDUCTIONS')
  if ((d.deductions ?? []).length === 0) tableRow('No deductions', 0)
  else for (const l of d.deductions) tableRow(l.label || 'Item', Number(l.amount) || 0)
  tableRow('Total deductions', totalDeductions, { bold: true })
  y -= 14

  // Net pay highlight box.
  page.drawRectangle({ x: MARGIN, y: y - 30, width: maxW, height: 40, color: NAVY })
  page.drawText('NET PAY', { x: MARGIN + 14, y: y - 12, size: 11, font: bold, color: rgb(1, 1, 1) })
  const netStr = `${d.currency} ${fmtMoney(net)}`
  page.drawText(netStr, { x: A4.w - MARGIN - 14 - bold.widthOfTextAtSize(netStr, 15), y: y - 15, size: 15, font: bold, color: rgb(1, 1, 1) })
  y -= 56

  // Bank / payment details.
  if (d.bank && (d.bank.iban || d.bank.bankName)) {
    page.drawText('PAYMENT DETAILS', { x: MARGIN, y, size: 9, font: bold, color: NAVY })
    y -= 15
    const bankRows: [string, string][] = [
      ['Account holder', d.bank.holder || d.crewName || '—'],
      ['Bank', [d.bank.bankName, d.bank.country].filter(Boolean).join(', ') || '—'],
      ['IBAN', d.bank.iban || '—'],
      ['BIC / SWIFT', d.bank.bic || '—'],
    ]
    for (const [k, v] of bankRows) {
      page.drawText(k, { x: MARGIN, y, size: 8.5, font, color: MUTED })
      page.drawText(v, { x: MARGIN + 110, y, size: 9.5, font, color: INK })
      y -= 15
    }
  }

  footer(page, font, `This payslip is computer-generated by Polaris and does not require a signature · ${d.crewName}`)
  return doc.save()
}
