/**
 * Generate Crew Placement PDFs (contracts & payslips) from a template's
 * {{placeholder}} body, rendered with pdf-lib. Worker/edge-safe.
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

/** Replace {{key}} tokens in a template body with values (missing → blank). */
export function fillTemplate(body: string, values: Record<string, string | number | null | undefined>): string {
  return (body ?? '').replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_m, k) => {
    const v = values[k]
    return v == null ? '' : String(v)
  })
}

/** Render a titled text document to a PDF (A4, word-wrapped). */
export async function buildTextPdf(title: string, text: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const A4 = { w: 595.28, h: 841.89 }
  const margin = 56
  const maxW = A4.w - margin * 2

  let page = doc.addPage([A4.w, A4.h])
  let y = A4.h - margin

  // Brand header
  page.drawText('JLS Yachts LLC', { x: margin, y, size: 16, font: bold, color: rgb(0.03, 0.26, 0.37) })
  y -= 16
  page.drawText('Crew Management', { x: margin, y, size: 9, font, color: rgb(0.4, 0.45, 0.5) })
  y -= 28
  page.drawText(title, { x: margin, y, size: 13, font: bold, color: rgb(0.1, 0.12, 0.15) })
  y -= 10
  page.drawLine({ start: { x: margin, y }, end: { x: A4.w - margin, y }, thickness: 0.75, color: rgb(0.8, 0.84, 0.88) })
  y -= 22

  const size = 10.5
  const lineH = size * 1.5
  const wrap = (line: string): string[] => {
    if (line === '') return ['']
    const words = line.split(/\s+/)
    const out: string[] = []
    let cur = ''
    for (const w of words) {
      const test = cur ? `${cur} ${w}` : w
      if (font.widthOfTextAtSize(test, size) > maxW && cur) { out.push(cur); cur = w }
      else cur = test
    }
    if (cur) out.push(cur)
    return out
  }

  for (const raw of (text ?? '').split('\n')) {
    for (const line of wrap(raw)) {
      if (y < margin + lineH) { page = doc.addPage([A4.w, A4.h]); y = A4.h - margin }
      page.drawText(line, { x: margin, y, size, font, color: rgb(0.12, 0.14, 0.17) })
      y -= lineH
    }
  }

  // Footer on the last page
  page.drawText('Generated by Polaris — JLS Yachts', { x: margin, y: 28, size: 8, font, color: rgb(0.6, 0.64, 0.68) })
  return doc.save()
}
