-- Managed Boats: the client's RYA inspection checklists, and inventory matching.
--
-- 29 Sep 2026. The three RYA lists (Personal Water Craft / Powerboat / Cruising)
-- come from the operations team's "OPS Checklist.xlsx", item for item, keeping
-- the sheet's section, quantity/unit and RYA TC reference. The generic starter
-- items from 20260929140000 are removed; DMA and FMA stay empty until the
-- official lists arrive. Each boat's tick can also be linked to the inventory
-- row that satisfies it.

alter table public.orbit2_checklist_templates
  add column if not exists section text,
  add column if not exists qty     numeric,
  add column if not exists unit    text,
  add column if not exists ref     text;

alter table public.orbit2_boat_checklist
  add column if not exists inventory_item_id uuid references public.orbit2_boat_inventory(id) on delete set null;

-- Placeholders out (nothing has been ticked against them yet).
delete from public.orbit2_checklist_templates;

-- RYA - Personal Water Craft: 31 items
insert into public.orbit2_checklist_templates (regime, category, section, item, qty, unit, ref, sort_order) values
  ('rya', 'pwc', 'EQUIPMENT', 'Fire extinguisher', null, null, null, 1),
  ('rya', 'pwc', 'EQUIPMENT', 'Distress flares (2 orange smoke, 2 pinpoint red, or 2 day/night flares)(coastal)', null, null, null, 2),
  ('rya', 'pwc', 'EQUIPMENT', 'Torch', null, null, null, 3),
  ('rya', 'pwc', 'EQUIPMENT', 'Sharp knife, preferably serrated', null, null, null, 4),
  ('rya', 'pwc', 'EQUIPMENT', 'Tow rope, minimum 6m, floating, hi visibility line', null, null, null, 5),
  ('rya', 'pwc', 'EQUIPMENT', 'Waterproof first aid kit containing (minimum) 2 large wound dressings, 2 medium wound dressings and triangular bandages', null, null, null, 6),
  ('rya', 'pwc', 'EQUIPMENT', 'Small grapnel anchor', null, null, null, 7),
  ('rya', 'pwc', 'EQUIPMENT', 'Tool kit', null, null, null, 8),
  ('rya', 'pwc', 'EQUIPMENT', 'Spares', null, null, null, 9),
  ('rya', 'pwc', 'EQUIPMENT', 'Hand bearing compass', null, null, null, 10),
  ('rya', 'pwc', 'EQUIPMENT', 'Spare killcord', null, null, null, 11),
  ('rya', 'pwc', 'EQUIPMENT', 'Buoyancy aids comply with EN393/ISO12402-5 (50 Newton/Level 50) or USCG Type III PFD. From April 2022 Impact Buoyancy Aids required.', null, null, 'TCWP2', 12),
  ('rya', 'pwc', 'HULL', 'Clear of cracks and damage', null, null, null, 13),
  ('rya', 'pwc', 'HULL', 'D-rings secure', null, null, null, 14),
  ('rya', 'pwc', 'HULL', 'Handholds for passenger secure', null, null, null, 15),
  ('rya', 'pwc', 'STEERING + PROPULSION SYSTEM', 'Handlebars move freely', null, null, null, 16),
  ('rya', 'pwc', 'STEERING + PROPULSION SYSTEM', 'Nozzle moves freely in tune with handlebars', null, null, null, 17),
  ('rya', 'pwc', 'STEERING + PROPULSION SYSTEM', 'Gear lever moves freely', null, null, null, 18),
  ('rya', 'pwc', 'STEERING + PROPULSION SYSTEM', 'Bucket/clam shell moves smoothly', null, null, null, 19),
  ('rya', 'pwc', 'STEERING + PROPULSION SYSTEM', 'Impeller and wear ring in good condition', null, null, null, 20),
  ('rya', 'pwc', 'ENGINE BAY', 'Seals are in good condition', null, null, null, 21),
  ('rya', 'pwc', 'ENGINE BAY', 'Free of excessive corrosion', null, null, null, 22),
  ('rya', 'pwc', 'ENGINE BAY', 'Clear of oil or fuel', null, null, null, 23),
  ('rya', 'pwc', 'ENGINE BAY', 'Pipes, leads, battery are secure', null, null, null, 24),
  ('rya', 'pwc', 'ENGINE RUNNING', 'Starts and runs satisfactorily', null, null, null, 25),
  ('rya', 'pwc', 'ENGINE RUNNING', 'Killcord in good condition', null, null, 'TCPW1', 26),
  ('rya', 'pwc', 'ENGINE RUNNING', 'Killcord stops the engine', null, null, null, 27),
  ('rya', 'pwc', 'ENGINE RUNNING', 'Killcord used at all times', null, null, null, 28),
  ('rya', 'pwc', 'TRAILER', 'Trailer in serviceable condition', null, null, null, 29),
  ('rya', 'pwc', 'TRAILER', 'Winch strap fully operational', null, null, null, 30),
  ('rya', 'pwc', 'TEACHING RESOURCES', '4 x marker buoys of sufficient size and colour so as to be clearly visible in the prevailing conditions', null, null, null, 31);

-- RYA - Powerboat: 89 items
insert into public.orbit2_checklist_templates (regime, category, section, item, qty, unit, ref, sort_order) values
  ('rya', 'powerboat', 'EQUIPMENT', 'Paddles or oars (or alternate means of propulsion)', 2, 'Pcs', null, 1),
  ('rya', 'powerboat', 'EQUIPMENT', 'Bucket or bailer', 2, 'Pcs', null, 2),
  ('rya', 'powerboat', 'EQUIPMENT', 'Towline', 1, 'Pcs', null, 3),
  ('rya', 'powerboat', 'EQUIPMENT', 'Throwline', 1, 'Pcs', null, 4),
  ('rya', 'powerboat', 'EQUIPMENT', 'Tool kit', 1, 'Set', null, 5),
  ('rya', 'powerboat', 'EQUIPMENT', 'Survival bag or TPA (thermo protective aid)', 2, 'Pcs', null, 6),
  ('rya', 'powerboat', 'EQUIPMENT', 'Waterproof first aid kit containing (minimum) 2 large wound dressings, 2 medium wound dressings and triangular bandages', null, null, null, 7),
  ('rya', 'powerboat', 'EQUIPMENT', 'Anchor and chain or warp', null, null, 'TCP4', 8),
  ('rya', 'powerboat', 'EQUIPMENT', 'Distress flares (2 orange smoke and 2 pinpoint red, or 2 day/night flares) (coastal RTCs)', null, null, null, 9),
  ('rya', 'powerboat', 'EQUIPMENT', 'Sharp knife, preferably serrated', null, null, null, 10),
  ('rya', 'powerboat', 'EQUIPMENT', 'Spare kill cord (except heavy displacement craft)', null, null, null, 11),
  ('rya', 'powerboat', 'EQUIPMENT', '1 Fire extinguisher 5A/34B serviced annually, in line with manufacturers’ recommendations, discharge test @ 5yr', null, null, null, 12),
  ('rya', 'powerboat', 'EQUIPMENT', 'VHF fixed or handheld', null, null, null, 13),
  ('rya', 'powerboat', 'EQUIPMENT', 'Radio emergency procedure card', null, null, null, 14),
  ('rya', 'powerboat', 'EQUIPMENT', 'Radar reflector must be carried on vessels fitted with an A-frame', null, null, null, 15),
  ('rya', 'powerboat', 'EQUIPMENT', 'Efficient fog sound signal', null, null, null, 16),
  ('rya', 'powerboat', 'EQUIPMENT', 'Laminated charts, (in date) or map of operating area (inland)', null, null, null, 17),
  ('rya', 'powerboat', 'EQUIPMENT', 'Tide tables (coastal)', null, null, null, 18),
  ('rya', 'powerboat', 'POWERBOAT LEVEL 2 COURSES', 'Compass, fixed or handheld', null, null, null, 19),
  ('rya', 'powerboat', 'POWERBOAT LEVEL 2 COURSES', 'Chartplotter or GPS, fixed or handheld', null, null, null, 20),
  ('rya', 'powerboat', 'SAFETY BOAT COURSES', 'Bridle secured to suitable strong points', null, null, null, 21),
  ('rya', 'powerboat', 'SAFETY BOAT COURSES', 'Sufficient modern dinghies and windsurfers available for use', null, null, null, 22),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'Fixed steering compass', null, null, null, 23),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'chartplotter or GPS – fixed', null, null, null, 24),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'VHF – fixed and handheld', null, null, null, 25),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'Fixed echo sounder', null, null, null, 26),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'Torch', null, null, null, 27),
  ('rya', 'powerboat', 'INTERMEDIATE AND ADVANCED COURSES', 'Navigation lights', null, null, null, 28),
  ('rya', 'powerboat', 'INSTRUCTOR POSITION', 'Unobstructed access to throttle and kill cord (PB1+2 only) for instructor', null, null, 'TCP6', 29),
  ('rya', 'powerboat', 'INSTRUCTOR POSITION', 'Secure helm position', null, null, 'TCP6', 30),
  ('rya', 'powerboat', 'INSTRUCTOR POSITION', 'Secure position for instructor and crew', null, null, 'TCP6', 31),
  ('rya', 'powerboat', 'INSTRUCTOR POSITION', 'Hand holds for all participants', null, null, 'TCP6', 32),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Engines serviced regularly and in good order', null, null, null, 33),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Outboards securely mounted', null, null, null, 34),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Throttle/gear changing mechanisms positive and reliable', null, null, null, 35),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Outboard engines must not slip out of gear or start in gear', null, null, null, 36),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Outboard engines must be capable of being locked down and raised', null, null, null, 37),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Fuel tanks must be securely fastened to boat', null, null, null, 38),
  ('rya', 'powerboat', 'ENGINES AND SAFETY SYSTEMS', 'Spare petrol containers clearly marked and readily jettisoned', null, null, null, 39),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Fuel cut off outside engine space', null, null, null, 40),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Sea cocks functioning', null, null, null, 41),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Seacocks piping fire resistant', null, null, null, 42),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Soft wood bungs for seacocks', null, null, null, 43),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Oil drip tray or containment', null, null, null, 44),
  ('rya', 'powerboat', 'ENGINE COMPARTMENT (if inboard – if petrol, consult RYA Training)', 'Bilge alarm fitted', null, null, null, 45),
  ('rya', 'powerboat', 'BATTERIES AND ELECTRICS', 'Batteries secure & ventilated', null, null, null, 46),
  ('rya', 'powerboat', 'SAFETY SYSTEMS', 'Kill switches fully functioning • Kill cords used at all times • Effective kill cord for student and instructor if teaching 8-11 year olds', null, null, null, 47),
  ('rya', 'powerboat', 'SAFETY SYSTEMS', 'All equipment suitably secured/stowed', null, null, null, 48),
  ('rya', 'powerboat', 'SAFETY SYSTEMS', 'Steering mechanism free, easy to use', null, null, null, 49),
  ('rya', 'powerboat', 'SAFETY SYSTEMS', 'Hydraulic steering checked for leaks', null, null, null, 50),
  ('rya', 'powerboat', 'TRAILER/LAUNCH TROLLEYS', 'Serviceable condition', null, null, null, 51),
  ('rya', 'powerboat', 'TRAILER/LAUNCH TROLLEYS', 'Winch strap fully operational', null, null, null, 52),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', '2 pin point red flares', null, null, null, 53),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Thermo Protective Aid (TPA) for each person', null, null, null, 54),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Searchlight with Morse capability', null, null, null, 55),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', '1 fire extinguisher 5A/34B', null, null, null, 56),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Engine space extinguisher (inboards)', null, null, null, 57),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Servicing annually /discharge test @ 5yrs', null, null, null, 58),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'First Aid Kit (Cat C) see MSN 1768', null, null, null, 59),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'First aid manual', null, null, null, 60),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Liferaft • Capacity - sufficient? • SOLAS B or approved ISAF part ll or ISO 9650 Part 1 - In date? • SOLAS “B” Grab bag', null, null, null, 61),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Liferaft Stowage • Stowed on deck (GRP only) • Hydrostatic release if on deck – in date • Valise - dedicated locker accessible to the deck annual service required', null, null, null, 62),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Man Overboard Equipment — 1 Lifebelt with vessels Name', null, null, 'TCP1', 63),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Man Overboard Equipment — Drogue on belt', null, null, 'TCP1', 64),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Man Overboard Equipment — Light on belt', null, null, 'TCP1', 65),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Man Overboard Equipment — Buoyant line(s) 18m min', null, null, 'TCP1', 66),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Man Overboard Equipment — Means of re-boarding vessel', null, null, 'TCP1', 67),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Bower + kedge anchor — Weight', null, null, 'TCP4', 68),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Bower + kedge anchor — Chain size', null, null, 'TCP4', 69),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Bower + kedge anchor — Warp size', null, null, 'TCP4', 70),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Bower + kedge anchor — At least 10 meters of chain', null, null, 'TCP4', 71),
  ('rya', 'powerboat', 'Advanced / Tender Operator — SAFETY EQUIPMENT', 'Towing warp. Kedge warp can be used as towing line', null, null, null, 72),
  ('rya', 'powerboat', 'Advanced / Tender Operator — MEANS OF DRAINAGE', 'Method of self-draining whilst moving ahead', null, null, null, 73),
  ('rya', 'powerboat', 'Advanced / Tender Operator — MEANS OF DRAINAGE', '2 buckets with lanyards', null, null, null, 74),
  ('rya', 'powerboat', 'Advanced / Tender Operator — HATCHES', 'Non skid', null, null, null, 75),
  ('rya', 'powerboat', 'Advanced / Tender Operator — HATCHES', 'Sufficient locking devices', null, null, null, 76),
  ('rya', 'powerboat', 'Advanced / Tender Operator — HATCHES', 'Weathertight', null, null, null, 77),
  ('rya', 'powerboat', 'Advanced / Tender Operator — LOCKERS', 'Positive catches', null, null, null, 78),
  ('rya', 'powerboat', 'Advanced / Tender Operator — LOCKERS', 'Personal gear stowage', null, null, null, 79),
  ('rya', 'powerboat', 'Advanced / Tender Operator — LOCKERS', 'Emergency steering (paddle)', null, null, null, 80),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Compass light', null, null, null, 81),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Radio emergency procedure card', null, null, null, 82),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Hand bearing compass', null, null, null, 83),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Up to date deviation card', null, null, null, 84),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Log', null, null, null, 85),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Almanac or sailing directions', null, null, null, 86),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Training manual', null, null, 'TCP2', 87),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'Maintenance manual', null, null, 'TCP3', 88),
  ('rya', 'powerboat', 'Advanced / Tender Operator — INSTRUMENTATION AND PUBLICATIONS', 'SOLAS No. 1 x 1 or No 2 x 2 Cards', null, null, null, 89);

-- RYA - Cruising: 150 items
insert into public.orbit2_checklist_templates (regime, category, section, item, qty, unit, ref, sort_order) values
  ('rya', 'cruising', 'Navigation Lights', 'Stern', null, null, null, 1),
  ('rya', 'cruising', 'Navigation Lights', 'Sidelights', null, null, null, 2),
  ('rya', 'cruising', 'Navigation Lights', 'Masthead', null, null, null, 3),
  ('rya', 'cruising', 'Navigation Lights', 'Anchor', null, null, null, 4),
  ('rya', 'cruising', 'Anchors', 'Main', null, null, 'TCC7', 5),
  ('rya', 'cruising', 'Anchors', 'Weight', null, null, 'TCC7', 6),
  ('rya', 'cruising', 'Anchors', 'Chain diameter', null, null, 'TCC7', 7),
  ('rya', 'cruising', 'Anchors', 'Warp diameter', null, null, 'TCC7', 8),
  ('rya', 'cruising', 'Anchors', '≥10m of chain, shackle wired', null, null, 'TCC7', 9),
  ('rya', 'cruising', 'Anchors', 'Anchors Secure', null, null, 'TCC7', 10),
  ('rya', 'cruising', 'Anchors', 'Kedge', null, null, 'TCC7', 11),
  ('rya', 'cruising', 'Anchors', 'Weight', null, null, 'TCC7', 12),
  ('rya', 'cruising', 'Anchors', 'Chain diameter', null, null, 'TCC7', 13),
  ('rya', 'cruising', 'Anchors', 'Warp diameter', null, null, 'TCC7', 14),
  ('rya', 'cruising', 'Anchors', '≥10m of chain, shackle wired', null, null, 'TCC7', 15),
  ('rya', 'cruising', 'Anchors', 'Anchors Secure', null, null, 'TCC7', 16),
  ('rya', 'cruising', 'Guardrails', 'Secure & serviceable', null, null, 'TCC16', 17),
  ('rya', 'cruising', 'Guardrails', 'Height at least 600mm', null, null, 'TCC16', 18),
  ('rya', 'cruising', 'RADAR Reflector (Fitted or hoisted)', 'Conforms to ISO 8729', null, null, null, 19),
  ('rya', 'cruising', 'Sailing Vessels only — Spinnaker pole', 'Fittings serviceable', null, null, 'TCC13', 20),
  ('rya', 'cruising', 'Sailing Vessels only — Spinnaker pole', 'Sufficient lines to triangulate', null, null, 'TCC13', 21),
  ('rya', 'cruising', 'Sailing Vessels only — Mast & Boom', 'Standing rigging, halyards, gooseneck, kicker, chainplates, deck glands, blocks & sheaves', null, null, 'TCC13', 22),
  ('rya', 'cruising', 'Sailing Vessels only — Deck Fittings', 'Genoa track, cars & sheets', null, null, null, 23),
  ('rya', 'cruising', 'Sailing Vessels only — Deck Fittings', 'Main sheet, sheaves & tackle', null, null, null, 24),
  ('rya', 'cruising', 'Sailing Vessels only — Deck Fittings', 'Winches & handles', null, null, null, 25),
  ('rya', 'cruising', 'Sailing Vessels only — Deck Fittings', 'Jammers/clutches', null, null, null, 26),
  ('rya', 'cruising', 'Sailing Vessels only — Sails (Condition)', 'Genoa, UV strip & roller reefing gear', null, null, null, 27),
  ('rya', 'cruising', 'Sailing Vessels only — Sails (Condition)', 'Mainsail & reefing pennants', null, null, null, 28),
  ('rya', 'cruising', 'Jackstays', 'If webbing, is stitching sound?', null, null, 'TCC16', 29),
  ('rya', 'cruising', 'Jackstays', 'Fitted on exposed deck areas (M)', null, null, 'TCC16', 30),
  ('rya', 'cruising', 'Fenders & warps', 'Sufficient & in good condition', null, null, null, 31),
  ('rya', 'cruising', 'Liferaft', 'Capacity Sufficient?', null, null, 'TCC6', 32),
  ('rya', 'cruising', 'Liferaft', 'SOLAS B or ISO 9650-1', null, null, 'TCC6', 33),
  ('rya', 'cruising', 'Liferaft', 'SOLAS B grab bag if ISO 9650-1', null, null, 'TCC6', 34),
  ('rya', 'cruising', 'Liferaft', 'In date hydrostatic release if on deck', null, null, 'TCC6', 35),
  ('rya', 'cruising', 'Liferaft', 'In dedicated locker if valise', null, null, 'TCC6', 36),
  ('rya', 'cruising', 'Liferaft', 'Serviced/Certificate in date', null, null, 'TCC6', 37),
  ('rya', 'cruising', 'External Lockers', 'Positive Catches', null, null, null, 38),
  ('rya', 'cruising', 'Man Overboard Equipment', 'Two lifebuoys with vessel name', null, null, 'TCC15', 39),
  ('rya', 'cruising', 'Man Overboard Equipment', 'Drogue on each lifebuoy', null, null, 'TCC15', 40),
  ('rya', 'cruising', 'Man Overboard Equipment', 'Working Light on each lifebuoy', null, null, 'TCC15', 41),
  ('rya', 'cruising', 'Man Overboard Equipment', '18m buoyant line attached to one', null, null, 'TCC15', 42),
  ('rya', 'cruising', 'Man Overboard Equipment', 'Rigid danbuoy attached to one (S)', null, null, 'TCC15', 43),
  ('rya', 'cruising', 'Shore Power Lead', 'Safe & satisfactory condition', null, null, null, 44),
  ('rya', 'cruising', 'Gas Locker (if fitted)', 'Ventilated outboard & drain clear', null, null, null, 45),
  ('rya', 'cruising', 'Gas Locker (if fitted)', 'Cylinders secure', null, null, null, 46),
  ('rya', 'cruising', 'Gas Locker (if fitted)', 'Gas pipe condition/in date', null, null, null, 47),
  ('rya', 'cruising', 'Petrol (if carried)', 'In overboard drained stowage', null, null, null, 48),
  ('rya', 'cruising', 'Petrol (if carried)', 'Container prominently marked', null, null, null, 49),
  ('rya', 'cruising', 'Boarding Ladder', 'Adequate means of boarding vessel', null, null, null, 50),
  ('rya', 'cruising', 'Emergency Steering (Wheel Only)', 'Emergency Tiller', null, null, null, 51),
  ('rya', 'cruising', 'Emergency Steering (Wheel Only)', 'Hydraulic bypass (if applicable) (M)', null, null, null, 52),
  ('rya', 'cruising', 'Distress Flares', '6 Handheld Pinpoint Red', null, null, 'TCC4', 53),
  ('rya', 'cruising', 'Distress Flares', '4 Red parachute or 406 EPIRB', null, null, 'TCC4', 54),
  ('rya', 'cruising', 'Distress Flares', '2 Buoyant/Handheld Smoke', null, null, 'TCC4', 55),
  ('rya', 'cruising', 'Compass Light', 'Working (2x if dual helm)', null, null, null, 56),
  ('rya', 'cruising', 'Towing warp', 'Suitable long warp or kedge warp', null, null, null, 57),
  ('rya', 'cruising', 'Bilge Pumps', '1 x on deck, 1 x below deck', null, null, null, 58),
  ('rya', 'cruising', 'Emergency Buckets', '2 strong buckets with lanyards', null, null, null, 59),
  ('rya', 'cruising', 'Emergency Water', '2 litres per person, clearly marked', null, null, null, 60),
  ('rya', 'cruising', 'Day Shapes (fitted with lanyards)', 'Anchor Ball (2 if over 12m)', null, null, null, 61),
  ('rya', 'cruising', 'Day Shapes (fitted with lanyards)', 'Motor Sailing Cone (S)', null, null, null, 62),
  ('rya', 'cruising', 'Dinghy (Comp. Crew/Helmsman Courses)', 'Serviceable and available for course training', null, null, null, 63),
  ('rya', 'cruising', 'Cockpit & Companionway (S)', 'Safety line attachment points', null, null, null, 64),
  ('rya', 'cruising', 'Cockpit & Companionway (S)', 'Means of securing washboards', null, null, null, 65),
  ('rya', 'cruising', 'Engine Compartment', 'Compartment Clean & oil free', null, null, 'TCC1', 66),
  ('rya', 'cruising', 'Engine Compartment', 'Oil drip tray or containment', null, null, 'TCC1', 67),
  ('rya', 'cruising', 'Engine Compartment', 'Raw water pipes fire retardant', null, null, 'TCC1', 68),
  ('rya', 'cruising', 'Engine Compartment', 'Seacock(s) functioning', null, null, 'TCC1', 69),
  ('rya', 'cruising', 'Engine Compartment', 'Fuel isolator outside engine space', null, null, 'TCC1', 70),
  ('rya', 'cruising', 'Engine Compartment', 'Bilge Alarm(s) functional (M)', null, null, 'TCC1', 71),
  ('rya', 'cruising', 'Engine Spares', 'Alternator drive Belt', null, null, null, 72),
  ('rya', 'cruising', 'Engine Spares', 'Primary & secondary fuel filters', null, null, null, 73),
  ('rya', 'cruising', 'Engine Spares', 'Water pump impeller', null, null, null, 74),
  ('rya', 'cruising', 'Batteries & Electrics', 'Independent engine battery', null, null, null, 75),
  ('rya', 'cruising', 'Batteries & Electrics', 'Batteries secure and ventilated', null, null, null, 76),
  ('rya', 'cruising', 'Galley', 'Food storage & prep. areas hygienic', null, null, 'TCC11', 77),
  ('rya', 'cruising', 'Galley', 'Cooking & eating utensils clean', null, null, 'TCC11', 78),
  ('rya', 'cruising', 'Galley', 'Storage locker latches positive', null, null, 'TCC11', 79),
  ('rya', 'cruising', 'Galley', 'Food hygiene guidelines displayed', null, null, 'TCC11', 80),
  ('rya', 'cruising', 'Galley', 'Sink seacock(s) functional', null, null, 'TCC10', 81),
  ('rya', 'cruising', 'Galley', 'Remote gas tap', null, null, 'TCC10', 82),
  ('rya', 'cruising', 'Galley', 'Cooker gimbals lockable (S)', null, null, 'TCC10', 83),
  ('rya', 'cruising', 'Galley', 'Flame failure on all burners', null, null, 'TCC10', 84),
  ('rya', 'cruising', 'Galley', 'Gas pipe condition/in date', null, null, 'TCC10', 85),
  ('rya', 'cruising', 'Galley', 'Gas emergency action card displayed', null, null, 'TCC10', 86),
  ('rya', 'cruising', 'Galley', 'Functioning gas detector/alarm', null, null, 'TCC10', 87),
  ('rya', 'cruising', 'Galley', 'Curtains not in range of burners', null, null, 'TCC10', 88),
  ('rya', 'cruising', 'Galley', 'Fire blanket immediately accessible', null, null, 'TCC10', 89),
  ('rya', 'cruising', 'Galley', 'Suitable fresh water supply', null, null, 'TCC10', 90),
  ('rya', 'cruising', 'Heads/Shower Rooms', 'Heads clean & hygienic', null, null, null, 91),
  ('rya', 'cruising', 'Heads/Shower Rooms', 'Seacocks functioning', null, null, null, 92),
  ('rya', 'cruising', 'Hatches & Portlights', 'Secure & weathertight', null, null, 'TCC2', 93),
  ('rya', 'cruising', 'Hatches & Portlights', 'Non-slip', null, null, 'TCC2', 94),
  ('rya', 'cruising', 'Hatches & Portlights', 'Appropriate Signage', null, null, 'TCC2', 95),
  ('rya', 'cruising', 'Fire Extinguishers (UK BS EN2 fire classification system or equivalent standard)', '13A/113B in any communal area', null, null, null, 96),
  ('rya', 'cruising', 'Fire Extinguishers (UK BS EN2 fire classification system or equivalent standard)', 'Engine Space extinguisher or access port for 13A/113B hosed extinguisher', null, null, null, 97),
  ('rya', 'cruising', 'Fire Extinguishers (UK BS EN2 fire classification system or equivalent standard)', 'Minimum 5A/34B at entrance to each CCPCN, DSPCN, DSN, YSN accommodation space', null, null, null, 98),
  ('rya', 'cruising', 'Fire Extinguishers (UK BS EN2 fire classification system or equivalent standard)', 'Serviced Annually', null, null, null, 99),
  ('rya', 'cruising', 'Fire Extinguishers (UK BS EN2 fire classification system or equivalent standard)', 'Discharge test/Replaced after 5 years', null, null, null, 100),
  ('rya', 'cruising', 'Cabins', 'Suitable berths for use at sea', null, null, null, 101),
  ('rya', 'cruising', 'Cabins', 'Ventilation', null, null, null, 102),
  ('rya', 'cruising', 'Cabins', '2 exits or smoke alarm fitted', null, null, null, 103),
  ('rya', 'cruising', 'Cabins', 'Emergency torch functional', null, null, null, 104),
  ('rya', 'cruising', 'Cabins', 'Locker stowage clean', null, null, null, 105),
  ('rya', 'cruising', 'Stormsails (S)', 'Trysail or mainsail reefed to 40%', null, null, 'TCC12', 106),
  ('rya', 'cruising', 'Stormsails (S)', 'Storm jib', null, null, null, 107),
  ('rya', 'cruising', 'First Aid', 'Category C First Aid kit in date', null, null, 'MSN1768', 108),
  ('rya', 'cruising', 'First Aid', 'RYA First Aid book or latest edition St. John’s/Red Cross/St. Andrew’s', null, null, 'MSN1768', 109),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Electronic Chart System with up to date charts', null, null, 'TCC3', 110),
  ('rya', 'cruising', 'Instrumentation & Publications', 'RADAR', null, null, 'TCC14', 111),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Fixed VHF radio', null, null, 'TCC14', 112),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Handheld VHF radio (with charger)', null, null, 'TCC14', 113),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Emergency VHF aerial', null, null, 'TCC14', 114),
  ('rya', 'cruising', 'Instrumentation & Publications', 'NAVTEX or separate radio for weather forecasts', null, null, 'TCC14', 115),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Radio emergency procedure card', null, null, 'TCC14', 116),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Hand bearing compass', null, null, 'TCC14', 117),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Current deviation card(s)', null, null, 'TCC14', 118),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Adequate chart table', null, null, 'TCC14', 119),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Up to date chart coverage', null, null, 'TCC14', 120),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Almanac or Sailing Directions', null, null, 'TCC14', 121),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Echo Sounder', null, null, 'TCC14', 122),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Speed Log', null, null, 'TCC14', 123),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Anemometer', null, null, 'TCC14', 124),
  ('rya', 'cruising', 'Instrumentation & Publications', 'Barometer', null, null, 'TCC14', 125),
  ('rya', 'cruising', 'Safety & General Equipment', 'Sound signal (foghorn)', null, null, 'TCC17', 126),
  ('rya', 'cruising', 'Safety & General Equipment', 'Searchlight with Morse capability', null, null, 'TCC17', 127),
  ('rya', 'cruising', 'Safety & General Equipment', 'Softwood bungs for seacocks', null, null, 'TCC17', 128),
  ('rya', 'cruising', 'Safety & General Equipment', 'Suitable rig cutting gear e.g. wire cutter, hacksaw & spare blades etc.', null, null, 'TCC17', 129),
  ('rya', 'cruising', 'Safety & General Equipment', 'Adequate tool kit', null, null, 'TCC17', 130),
  ('rya', 'cruising', 'Safety & General Equipment', 'Spares box inc. shackles, insulation tape, split pins, nuts/bolts etc.', null, null, 'TCC17', 131),
  ('rya', 'cruising', 'Safety & General Equipment', 'CO Alarm fitted/In date', null, null, 'TCC17', 132),
  ('rya', 'cruising', 'Safety & General Equipment', 'Sail repair kit (S)', null, null, 'TCC17', 133),
  ('rya', 'cruising', 'Survival Equipment', 'Lifejackets for complement + 2', null, null, 'TCC5', 134),
  ('rya', 'cruising', 'Survival Equipment', 'Service certificate in date', null, null, 'TCC5', 135),
  ('rya', 'cruising', 'Survival Equipment', 'Lights fitted (not reqd. in spare LJs)', null, null, 'TCC5', 136),
  ('rya', 'cruising', 'Survival Equipment', 'Training manual', null, null, 'TCC8', 137),
  ('rya', 'cruising', 'Survival Equipment', 'Maintenance manual', null, null, 'TCC9', 138),
  ('rya', 'cruising', 'Survival Equipment', 'TPAs for complement', null, null, null, 139),
  ('rya', 'cruising', 'Survival Equipment', 'SOLAS No.1 & 2 cards', null, null, null, 140),
  ('rya', 'cruising', 'Teaching Resources', 'RYA Logbooks available', null, null, null, 141),
  ('rya', 'cruising', 'Teaching Resources', 'Appropriate course notes available: CCPCN, DSPCN, DSN, YSN', null, null, null, 142),
  ('rya', 'cruising', 'Motor Vessels only — Electronics', 'RADAR & plotting sheets', null, null, 'TCC3', 143),
  ('rya', 'cruising', 'Motor Vessels only — Systems', 'Bow thruster (if applicable)', null, null, null, 144),
  ('rya', 'cruising', 'Motor Vessels only — Systems', 'Power trim (if applicable)', null, null, null, 145),
  ('rya', 'cruising', 'Motor Vessels only — Systems', 'Trim tabs (if applicable)', null, null, null, 146),
  ('rya', 'cruising', 'Motor Vessels only — Engine Instrumentation Operational', 'Rev Counter (s)', null, null, null, 147),
  ('rya', 'cruising', 'Motor Vessels only — Engine Instrumentation Operational', 'Oil Pressure', null, null, null, 148),
  ('rya', 'cruising', 'Motor Vessels only — Engine Instrumentation Operational', 'Water temperature', null, null, null, 149),
  ('rya', 'cruising', 'Motor Vessels only — Engine Instrumentation Operational', 'Engine running hours log', null, null, null, 150);
