// AUTO-GENERATED by scripts/generate-changelog.mjs — do not edit by hand.
// Regenerated on every build from Conventional Commit history.

import type { Release } from "@/components/changelog-page";

export const GENERATED_RELEASES: Release[] = [
  {
    "version": "2.3.0",
    "date": "2026-06-10",
    "entries": [
      {
        "type": "fix",
        "title": "Yachts SharePoint sync now does a full pull every run"
      },
      {
        "type": "fix",
        "title": "Resolve SharePoint sync errors when list rows share a name or reference"
      },
      {
        "type": "feature",
        "title": "Instant app-to-SharePoint write-back on save for permits, small boats, crew and visas"
      },
      {
        "type": "feature",
        "title": "2-way SharePoint sync — outbound write-back engine + safe hourly reverse-delta + dedicated hourly cron"
      },
      {
        "type": "feature",
        "title": "Add Licensing page under Yacht IT Solutions (yacht software/IT license tracking)"
      },
      {
        "type": "feature",
        "title": "Build UAE country info page with 10-step process flow"
      },
      {
        "type": "feature",
        "title": "Add HandbookLink component and POLARIS_VISA_HANDBOOK spec"
      },
      {
        "type": "fix",
        "title": "Sanitize numeric yacht fields + drop non-existent small_boats.reg_no"
      },
      {
        "type": "feature",
        "title": "Improve Gate Pass auto-mapping (Gate Pass Date->issue_date, Token No->permit_number, Company/Duration->notes)"
      },
      {
        "type": "fix",
        "title": "Auto-load columns when editing a sync, preserve existing mapping, block empty-mapping saves"
      },
      {
        "type": "feature",
        "title": "Add Crew Members as a SharePoint sync target (for the Visa crew list)"
      },
      {
        "type": "feature",
        "title": "Visa Module v1 — 7-country wizard, compliance monitor, Leo integration"
      },
      {
        "type": "fix",
        "title": "Drop --frozen-lockfile so deploys don't fail (no bun.lock committed)"
      },
      {
        "type": "fix",
        "title": "SharePoint sync mapping dropdown uses the selected target's fields, not always Yachts"
      },
      {
        "type": "feature",
        "title": "Add Visa Applications as a SharePoint sync target"
      },
      {
        "type": "feature",
        "title": "Leo dashboard — proactive briefing on every login"
      },
      {
        "type": "fix",
        "title": "Correct developer list — Matt Peeters + Mike Fetton only; Tighe Fetton pending"
      },
      {
        "type": "feature",
        "title": "Build Leo AI engine — streaming briefing + chat"
      },
      {
        "type": "feature",
        "title": "Update Polaris tagline to Yacht Concierge & Operational Platform"
      },
      {
        "type": "feature",
        "title": "Align auth page gradient and working indicator to Polaris tokens"
      },
      {
        "type": "feature",
        "title": "Polaris dark-first brand system"
      }
    ]
  },
  {
    "version": "2.2.0",
    "date": "2026-06-09",
    "entries": [
      {
        "type": "feature",
        "title": "Add live AIS vessel tracking columns to Vessel Overview (Live Location, Underway, Departed, Arrived)"
      },
      {
        "type": "fix",
        "title": "Surface real Supabase admin errors in e-Sign instead of masking as 'Document not found'"
      },
      {
        "type": "feature",
        "title": "Mirror visa document uploads to SharePoint Crew Visas folder"
      },
      {
        "type": "fix",
        "title": "New Visa button now opens the wizard; add CI deploy + team presence overlay"
      },
      {
        "type": "feature",
        "title": "Rebrand to Polaris, add Leo AI bubble & Permit Command Centre"
      }
    ]
  }
];
